logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Music Extended"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Background play' 'Bitrate default value' 'Certificate spoof' 'Disable auto captions' 'Enable black navigation bar' 'Enable color match player' 'Enable force minimized player' 'Enable minimized playback' 'Enable new player background' 'Enable old style library shelf' 'Enable old style miniplayer' 'Enable opus codec' 'Enable playback speed' 'Enable sleep timer' 'Enable zen mode' 'Exclusive audio playback' 'Hide cast button' 'Hide general ads' 'Hide get premium' 'Remember playback speed' 'Remember repeat state' 'Remember shuffle state' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'SponsorBlock'"
exclusive-patches = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Add splash animation' 'Ambient mode switch' 'Append time stamps information' 'Disable auto captions' 'Disable haptic feedback' 'Disable pip notification' 'Disable shorts on startup' 'Enable bottom player gestures' 'Enable external browser' 'Enable gradient loading screen' 'Enable minimized playback' 'Enable new splash animation' 'Enable open links directly' 'Enable seekbar tapping' 'Enable song search' 'Hide floating microphone' 'Hide general ads' 'Hide video ads' 'MaterialYou' 'Overlay buttons' 'Quick actions components' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'Shorts outline button' 'SponsorBlock' 'Spoof device dimensions' 'Spoof player parameters'"
exclusive-patches = true
